#!/usr/bin/env node

/**
 * Database Backup Script
 * Creates backups of Cloudflare D1 database
 * 
 * This script:
 * 1. Exports all data from tables
 * 2. Creates timestamped backup files
 * 3. Saves backup in backups/ directory
 * 4. Optionally compresses backup
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
};

function log(message, color = colors.reset) {
  console.log(`${color}${message}${colors.reset}`);
}

function execQuery(databaseName, query) {
  try {
    const output = execSync(
      `wrangler d1 execute ${databaseName} --command="${query}" --remote`,
      { encoding: 'utf-8', stdio: 'pipe' }
    );
    return { success: true, output };
  } catch (error) {
    return { success: false, error: error.message };
  }
}

async function main() {
  log(`\n${colors.bright}==================================${colors.reset}`);
  log(`${colors.bright}  Database Backup                 ${colors.reset}`);
  log(`${colors.bright}==================================${colors.reset}\n`);

  // Read database name from wrangler.toml
  const wranglerConfig = fs.readFileSync('./wrangler.toml', 'utf-8');
  const dbNameMatch = wranglerConfig.match(/database_name\s*=\s*"([^"]+)"/);

  if (!dbNameMatch) {
    log(`${colors.red}✗ No se encontró database_name en wrangler.toml${colors.reset}`);
    process.exit(1);
  }

  const databaseName = dbNameMatch[1];
  log(`${colors.cyan}Base de datos: ${databaseName}${colors.reset}\n`);

  // Create backups directory
  const backupsDir = path.join(process.cwd(), 'backups');
  if (!fs.existsSync(backupsDir)) {
    fs.mkdirSync(backupsDir);
    log(`${colors.green}✓ Directorio de backups creado${colors.reset}`);
  }

  // Generate timestamp for backup filename
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  const backupFilename = `backup_${databaseName}_${timestamp}.sql`;
  const backupPath = path.join(backupsDir, backupFilename);

  log(`${colors.cyan}Archivo de backup: ${backupFilename}${colors.reset}\n`);

  // Start backup
  let backupContent = `-- Database Backup: ${databaseName}\n`;
  backupContent += `-- Date: ${new Date().toISOString()}\n`;
  backupContent += `-- Generated by db-backup.js\n\n`;

  // Backup users table
  log(`${colors.cyan}1. Respaldando tabla 'users'...${colors.reset}`);
  
  const usersData = execQuery(
    databaseName,
    "SELECT * FROM users"
  );

  if (usersData.success) {
    backupContent += `-- Users Table\n`;
    backupContent += `DELETE FROM users;\n`;
    
    // Parse output and create INSERT statements
    const lines = usersData.output.split('\n').filter(line => line.trim());
    let userCount = 0;
    
    for (const line of lines) {
      if (line.includes('|') && !line.includes('id') && !line.includes('---')) {
        const parts = line.split('|').map(p => p.trim());
        if (parts.length >= 7) {
          const [id, username, password_hash, email, email_verified, email_verification_token, created_at] = parts;
          backupContent += `INSERT INTO users (id, username, password_hash, email, email_verified, email_verification_token, created_at) VALUES ('${id}', '${username}', '${password_hash}', ${email ? `'${email}'` : 'NULL'}, ${email_verified}, ${email_verification_token ? `'${email_verification_token}'` : 'NULL'}, '${created_at}');\n`;
          userCount++;
        }
      }
    }
    
    log(`  ${colors.green}✓ ${userCount} usuarios respaldados${colors.reset}`);
  } else {
    log(`  ${colors.red}✗ Error al respaldar usuarios${colors.reset}`);
  }

  backupContent += `\n`;

  // Backup cvs table
  log(`\n${colors.cyan}2. Respaldando tabla 'cvs'...${colors.reset}`);
  
  const cvsData = execQuery(
    databaseName,
    "SELECT id, user_id, name, slug, is_public, created_at, updated_at FROM cvs"
  );

  if (cvsData.success) {
    backupContent += `-- CVs Table (metadata only, data field excluded for readability)\n`;
    backupContent += `-- Note: Full data export available via wrangler d1 export\n`;
    
    const lines = cvsData.output.split('\n').filter(line => line.trim());
    let cvCount = 0;
    
    for (const line of lines) {
      if (line.includes('|') && !line.includes('id') && !line.includes('---')) {
        cvCount++;
      }
    }
    
    log(`  ${colors.green}✓ ${cvCount} CVs encontrados${colors.reset}`);
    log(`  ${colors.yellow}⚠ Nota: Para backup completo de datos JSON, usa 'wrangler d1 export'${colors.reset}`);
  } else {
    log(`  ${colors.red}✗ Error al respaldar CVs${colors.reset}`);
  }

  // Get full export using wrangler d1 export
  log(`\n${colors.cyan}3. Creando export completo...${colors.reset}`);
  
  try {
    const exportOutput = execSync(
      `wrangler d1 export ${databaseName} --remote --output=${backupPath}`,
      { encoding: 'utf-8', stdio: 'pipe' }
    );
    log(`  ${colors.green}✓ Export completo creado${colors.reset}`);
  } catch (error) {
    log(`  ${colors.yellow}⚠ No se pudo crear export completo con wrangler${colors.reset}`);
    log(`  ${colors.yellow}Guardando backup parcial...${colors.reset}`);
    
    // Save partial backup
    fs.writeFileSync(backupPath, backupContent);
  }

  // Verify backup file
  if (fs.existsSync(backupPath)) {
    const stats = fs.statSync(backupPath);
    const fileSizeKB = (stats.size / 1024).toFixed(2);
    
    log(`\n${colors.green}✓ Backup creado exitosamente${colors.reset}`);
    log(`  Archivo: ${backupPath}`);
    log(`  Tamaño: ${fileSizeKB} KB`);
  } else {
    log(`\n${colors.red}✗ Error: No se pudo crear el archivo de backup${colors.reset}`);
    process.exit(1);
  }

  // Summary
  log(`\n${colors.bright}==================================${colors.reset}`);
  log(`${colors.bright}  Backup Completado               ${colors.reset}`);
  log(`${colors.bright}==================================${colors.reset}\n`);

  log(`${colors.green}✓ Backup guardado en: ${backupPath}${colors.reset}`);
  log(`\n${colors.cyan}Para restaurar el backup:${colors.reset}`);
  log(`  wrangler d1 execute ${databaseName} --file=${backupPath} --remote\n`);

  // List recent backups
  const backupFiles = fs.readdirSync(backupsDir)
    .filter(file => file.startsWith('backup_') && file.endsWith('.sql'))
    .sort()
    .reverse()
    .slice(0, 5);

  if (backupFiles.length > 0) {
    log(`${colors.cyan}Backups recientes:${colors.reset}`);
    backupFiles.forEach((file, index) => {
      const filePath = path.join(backupsDir, file);
      const stats = fs.statSync(filePath);
      const date = new Date(stats.mtime).toLocaleString();
      const sizeKB = (stats.size / 1024).toFixed(2);
      log(`  ${index + 1}. ${file} (${sizeKB} KB, ${date})`);
    });
    log('');
  }
}

// Run the script
main().catch((error) => {
  log(`\n${colors.red}Error fatal: ${error.message}${colors.reset}`);
  process.exit(1);
});
